global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]

  # - job_name: "dotnet-core-exporter"
  #   static_configs:
  #     - targets: ["dotnet-core-exporter:80"]

  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]